// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package dbgen

import (
	"context"
)

const clearConnectionHeaders = `-- name: ClearConnectionHeaders :exec
DELETE FROM saved_connection_headers WHERE connection_id=?
`

func (q *Queries) ClearConnectionHeaders(ctx context.Context, connectionID string) error {
	_, err := q.db.ExecContext(ctx, clearConnectionHeaders, connectionID)
	return err
}

const clearConnectionUses = `-- name: ClearConnectionUses :exec
DELETE FROM saved_connection_uses
`

func (q *Queries) ClearConnectionUses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearConnectionUses)
	return err
}

const clearSelectedConnections = `-- name: ClearSelectedConnections :exec
DELETE FROM selected_connections
`

func (q *Queries) ClearSelectedConnections(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearSelectedConnections)
	return err
}

const deleteSavedConnection = `-- name: DeleteSavedConnection :exec
DELETE FROM saved_connections WHERE id=?
`

func (q *Queries) DeleteSavedConnection(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSavedConnection, id)
	return err
}

const listConnectionHeaders = `-- name: ListConnectionHeaders :many
SELECT connection_id,name,value FROM saved_connection_headers ORDER BY connection_id,name LIMIT 4097
`

func (q *Queries) ListConnectionHeaders(ctx context.Context) ([]SavedConnectionHeader, error) {
	rows, err := q.db.QueryContext(ctx, listConnectionHeaders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedConnectionHeader{}
	for rows.Next() {
		var i SavedConnectionHeader
		if err := rows.Scan(&i.ConnectionID, &i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionUses = `-- name: ListConnectionUses :many
SELECT connection_id,purpose FROM saved_connection_uses ORDER BY connection_id,purpose LIMIT 513
`

func (q *Queries) ListConnectionUses(ctx context.Context) ([]SavedConnectionUse, error) {
	rows, err := q.db.QueryContext(ctx, listConnectionUses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedConnectionUse{}
	for rows.Next() {
		var i SavedConnectionUse
		if err := rows.Scan(&i.ConnectionID, &i.Purpose); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedConnections = `-- name: ListSavedConnections :many
SELECT id,name,compatibility_profile,base_url,allow_insecure_http,authentication_mode,health_path,credential_account FROM saved_connections ORDER BY name,id LIMIT 129
`

func (q *Queries) ListSavedConnections(ctx context.Context) ([]SavedConnection, error) {
	rows, err := q.db.QueryContext(ctx, listSavedConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedConnection{}
	for rows.Next() {
		var i SavedConnection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CompatibilityProfile,
			&i.BaseUrl,
			&i.AllowInsecureHttp,
			&i.AuthenticationMode,
			&i.HealthPath,
			&i.CredentialAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelectedConnections = `-- name: ListSelectedConnections :many
SELECT purpose,connection_id FROM selected_connections ORDER BY purpose
`

func (q *Queries) ListSelectedConnections(ctx context.Context) ([]SelectedConnection, error) {
	rows, err := q.db.QueryContext(ctx, listSelectedConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectedConnection{}
	for rows.Next() {
		var i SelectedConnection
		if err := rows.Scan(&i.Purpose, &i.ConnectionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putConnectionHeader = `-- name: PutConnectionHeader :exec
INSERT INTO saved_connection_headers(connection_id,name,value) VALUES(?,?,?)
`

type PutConnectionHeaderParams struct {
	ConnectionID string
	Name         string
	Value        string
}

func (q *Queries) PutConnectionHeader(ctx context.Context, arg PutConnectionHeaderParams) error {
	_, err := q.db.ExecContext(ctx, putConnectionHeader, arg.ConnectionID, arg.Name, arg.Value)
	return err
}

const putConnectionUse = `-- name: PutConnectionUse :exec
INSERT INTO saved_connection_uses(connection_id,purpose) VALUES(?,?)
`

type PutConnectionUseParams struct {
	ConnectionID string
	Purpose      string
}

func (q *Queries) PutConnectionUse(ctx context.Context, arg PutConnectionUseParams) error {
	_, err := q.db.ExecContext(ctx, putConnectionUse, arg.ConnectionID, arg.Purpose)
	return err
}

const putSavedConnection = `-- name: PutSavedConnection :exec
INSERT INTO saved_connections(id,name,compatibility_profile,base_url,allow_insecure_http,authentication_mode,health_path,credential_account) VALUES(?,?,?,?,?,?,?,?)
ON CONFLICT(id) DO UPDATE SET name=excluded.name,compatibility_profile=excluded.compatibility_profile,base_url=excluded.base_url,allow_insecure_http=excluded.allow_insecure_http,authentication_mode=excluded.authentication_mode,health_path=excluded.health_path,credential_account=excluded.credential_account
`

type PutSavedConnectionParams struct {
	ID                   string
	Name                 string
	CompatibilityProfile string
	BaseUrl              string
	AllowInsecureHttp    int64
	AuthenticationMode   string
	HealthPath           string
	CredentialAccount    string
}

func (q *Queries) PutSavedConnection(ctx context.Context, arg PutSavedConnectionParams) error {
	_, err := q.db.ExecContext(ctx, putSavedConnection,
		arg.ID,
		arg.Name,
		arg.CompatibilityProfile,
		arg.BaseUrl,
		arg.AllowInsecureHttp,
		arg.AuthenticationMode,
		arg.HealthPath,
		arg.CredentialAccount,
	)
	return err
}

const seedCleanupConnection = `-- name: SeedCleanupConnection :exec
INSERT INTO saved_connections(id,name,compatibility_profile,base_url,allow_insecure_http,authentication_mode,health_path,credential_account) SELECT 'initial-cleanup','Post-processing',s.compatibility_profile,s.base_url,s.allow_insecure_http,CASE WHEN c.account<>'' THEN 'api-key' ELSE 'none' END,'',c.account FROM cleanup_settings s JOIN credential_refs c ON c.purpose='cleanup' WHERE s.base_url <> '' AND NOT EXISTS(SELECT 1 FROM saved_connections WHERE id='initial-cleanup')
`

func (q *Queries) SeedCleanupConnection(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedCleanupConnection)
	return err
}

const seedConnectionHeaders = `-- name: SeedConnectionHeaders :exec
INSERT INTO saved_connection_headers(connection_id,name,value) SELECT 'initial-stt',name,value FROM request_headers WHERE EXISTS(SELECT 1 FROM saved_connections WHERE id='initial-stt') ON CONFLICT(connection_id,name) DO NOTHING
`

func (q *Queries) SeedConnectionHeaders(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedConnectionHeaders)
	return err
}

const seedConnectionUses = `-- name: SeedConnectionUses :exec
INSERT INTO saved_connection_uses(connection_id,purpose) SELECT id,CASE id WHEN 'initial-stt' THEN 'stt' WHEN 'initial-cleanup' THEN 'cleanup' ELSE 'speech' END FROM saved_connections WHERE id IN ('initial-stt','initial-cleanup','initial-speech') ON CONFLICT DO NOTHING
`

func (q *Queries) SeedConnectionUses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedConnectionUses)
	return err
}

const seedSelectedConnections = `-- name: SeedSelectedConnections :exec
INSERT INTO selected_connections(purpose,connection_id) SELECT purpose,connection_id FROM saved_connection_uses WHERE connection_id IN ('initial-stt','initial-cleanup','initial-speech') ON CONFLICT(purpose) DO NOTHING
`

func (q *Queries) SeedSelectedConnections(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedSelectedConnections)
	return err
}

const seedSpeechConnection = `-- name: SeedSpeechConnection :exec
INSERT INTO saved_connections(id,name,compatibility_profile,base_url,allow_insecure_http,authentication_mode,health_path,credential_account) SELECT 'initial-speech','Speech playback',s.compatibility_profile,s.base_url,s.allow_insecure_http,s.authentication_mode,'',c.account FROM speech_settings s JOIN credential_refs c ON c.purpose='speech' WHERE s.base_url <> '' AND NOT EXISTS(SELECT 1 FROM saved_connections WHERE id='initial-speech')
`

func (q *Queries) SeedSpeechConnection(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedSpeechConnection)
	return err
}

const seedTranscriptionConnection = `-- name: SeedTranscriptionConnection :exec
INSERT INTO saved_connections(id,name,compatibility_profile,base_url,allow_insecure_http,authentication_mode,health_path,credential_account) SELECT 'initial-stt','Transcription',s.compatibility_profile,s.base_url,s.allow_insecure_http,s.authentication_mode,s.health_path,c.account FROM transcription_settings s JOIN credential_refs c ON c.purpose='stt' WHERE s.base_url <> '' AND NOT EXISTS(SELECT 1 FROM saved_connections WHERE id='initial-stt')
`

func (q *Queries) SeedTranscriptionConnection(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedTranscriptionConnection)
	return err
}

const seedVoiceSelection = `-- name: SeedVoiceSelection :exec
INSERT INTO selected_connections(purpose,connection_id) SELECT 'voice','initial-stt' WHERE EXISTS(SELECT 1 FROM saved_connections WHERE id='initial-stt') ON CONFLICT DO NOTHING
`

func (q *Queries) SeedVoiceSelection(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedVoiceSelection)
	return err
}

const seedVoiceUse = `-- name: SeedVoiceUse :exec
INSERT INTO saved_connection_uses(connection_id,purpose) SELECT 'initial-stt','voice' WHERE EXISTS(SELECT 1 FROM saved_connections WHERE id='initial-stt') ON CONFLICT DO NOTHING
`

func (q *Queries) SeedVoiceUse(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedVoiceUse)
	return err
}

const selectSavedConnection = `-- name: SelectSavedConnection :exec
INSERT INTO selected_connections(purpose,connection_id) VALUES(?,?) ON CONFLICT(purpose) DO UPDATE SET connection_id=excluded.connection_id
`

type SelectSavedConnectionParams struct {
	Purpose      string
	ConnectionID string
}

func (q *Queries) SelectSavedConnection(ctx context.Context, arg SelectSavedConnectionParams) error {
	_, err := q.db.ExecContext(ctx, selectSavedConnection, arg.Purpose, arg.ConnectionID)
	return err
}
