// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package dbgen

import (
	"context"
)

const clearConnectionHeaders = `-- name: ClearConnectionHeaders :exec
DELETE FROM saved_connection_headers WHERE connection_id=?
`

func (q *Queries) ClearConnectionHeaders(ctx context.Context, connectionID string) error {
	_, err := q.db.ExecContext(ctx, clearConnectionHeaders, connectionID)
	return err
}

const clearSelectedConnections = `-- name: ClearSelectedConnections :exec
DELETE FROM selected_connections
`

func (q *Queries) ClearSelectedConnections(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearSelectedConnections)
	return err
}

const deleteSavedConnection = `-- name: DeleteSavedConnection :exec
DELETE FROM saved_connections WHERE id=?
`

func (q *Queries) DeleteSavedConnection(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSavedConnection, id)
	return err
}

const listConnectionHeaders = `-- name: ListConnectionHeaders :many
SELECT connection_id,name,value FROM saved_connection_headers ORDER BY connection_id,name LIMIT 3073
`

func (q *Queries) ListConnectionHeaders(ctx context.Context) ([]SavedConnectionHeader, error) {
	rows, err := q.db.QueryContext(ctx, listConnectionHeaders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedConnectionHeader{}
	for rows.Next() {
		var i SavedConnectionHeader
		if err := rows.Scan(&i.ConnectionID, &i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedConnections = `-- name: ListSavedConnections :many
SELECT id,purpose,name,compatibility_profile,base_url,allow_insecure_http,authentication_mode,health_path,credential_account FROM saved_connections ORDER BY purpose,name,id LIMIT 97
`

func (q *Queries) ListSavedConnections(ctx context.Context) ([]SavedConnection, error) {
	rows, err := q.db.QueryContext(ctx, listSavedConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedConnection{}
	for rows.Next() {
		var i SavedConnection
		if err := rows.Scan(
			&i.ID,
			&i.Purpose,
			&i.Name,
			&i.CompatibilityProfile,
			&i.BaseUrl,
			&i.AllowInsecureHttp,
			&i.AuthenticationMode,
			&i.HealthPath,
			&i.CredentialAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelectedConnections = `-- name: ListSelectedConnections :many
SELECT purpose,connection_id FROM selected_connections ORDER BY purpose
`

func (q *Queries) ListSelectedConnections(ctx context.Context) ([]SelectedConnection, error) {
	rows, err := q.db.QueryContext(ctx, listSelectedConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectedConnection{}
	for rows.Next() {
		var i SelectedConnection
		if err := rows.Scan(&i.Purpose, &i.ConnectionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putConnectionHeader = `-- name: PutConnectionHeader :exec
INSERT INTO saved_connection_headers(connection_id,name,value) VALUES(?,?,?)
`

type PutConnectionHeaderParams struct {
	ConnectionID string
	Name         string
	Value        string
}

func (q *Queries) PutConnectionHeader(ctx context.Context, arg PutConnectionHeaderParams) error {
	_, err := q.db.ExecContext(ctx, putConnectionHeader, arg.ConnectionID, arg.Name, arg.Value)
	return err
}

const putSavedConnection = `-- name: PutSavedConnection :exec
INSERT INTO saved_connections(id,purpose,name,compatibility_profile,base_url,allow_insecure_http,authentication_mode,health_path,credential_account) VALUES(?,?,?,?,?,?,?,?,?)
ON CONFLICT(id) DO UPDATE SET name=excluded.name,compatibility_profile=excluded.compatibility_profile,base_url=excluded.base_url,allow_insecure_http=excluded.allow_insecure_http,authentication_mode=excluded.authentication_mode,health_path=excluded.health_path,credential_account=excluded.credential_account
`

type PutSavedConnectionParams struct {
	ID                   string
	Purpose              string
	Name                 string
	CompatibilityProfile string
	BaseUrl              string
	AllowInsecureHttp    int64
	AuthenticationMode   string
	HealthPath           string
	CredentialAccount    string
}

func (q *Queries) PutSavedConnection(ctx context.Context, arg PutSavedConnectionParams) error {
	_, err := q.db.ExecContext(ctx, putSavedConnection,
		arg.ID,
		arg.Purpose,
		arg.Name,
		arg.CompatibilityProfile,
		arg.BaseUrl,
		arg.AllowInsecureHttp,
		arg.AuthenticationMode,
		arg.HealthPath,
		arg.CredentialAccount,
	)
	return err
}

const seedCleanupConnection = `-- name: SeedCleanupConnection :exec
INSERT INTO saved_connections(id,purpose,name,compatibility_profile,base_url,allow_insecure_http,authentication_mode,health_path,credential_account) SELECT 'initial-cleanup','cleanup','Post-processing',s.compatibility_profile,s.base_url,s.allow_insecure_http,'none','',c.account FROM cleanup_settings s JOIN credential_refs c ON c.purpose='cleanup' WHERE s.base_url <> '' AND NOT EXISTS(SELECT 1 FROM saved_connections WHERE purpose='cleanup')
`

func (q *Queries) SeedCleanupConnection(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedCleanupConnection)
	return err
}

const seedConnectionHeaders = `-- name: SeedConnectionHeaders :exec
INSERT INTO saved_connection_headers(connection_id,name,value) SELECT 'initial-stt',name,value FROM request_headers WHERE EXISTS(SELECT 1 FROM saved_connections WHERE id='initial-stt') ON CONFLICT(connection_id,name) DO NOTHING
`

func (q *Queries) SeedConnectionHeaders(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedConnectionHeaders)
	return err
}

const seedSelectedConnections = `-- name: SeedSelectedConnections :exec
INSERT INTO selected_connections(purpose,connection_id) SELECT purpose,id FROM saved_connections WHERE id IN ('initial-stt','initial-cleanup','initial-speech') ON CONFLICT(purpose) DO NOTHING
`

func (q *Queries) SeedSelectedConnections(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedSelectedConnections)
	return err
}

const seedSpeechConnection = `-- name: SeedSpeechConnection :exec
INSERT INTO saved_connections(id,purpose,name,compatibility_profile,base_url,allow_insecure_http,authentication_mode,health_path,credential_account) SELECT 'initial-speech','speech','Speech playback',s.compatibility_profile,s.base_url,s.allow_insecure_http,s.authentication_mode,'',c.account FROM speech_settings s JOIN credential_refs c ON c.purpose='speech' WHERE s.base_url <> '' AND NOT EXISTS(SELECT 1 FROM saved_connections WHERE purpose='speech')
`

func (q *Queries) SeedSpeechConnection(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedSpeechConnection)
	return err
}

const seedTranscriptionConnection = `-- name: SeedTranscriptionConnection :exec
INSERT INTO saved_connections(id,purpose,name,compatibility_profile,base_url,allow_insecure_http,authentication_mode,health_path,credential_account) SELECT 'initial-stt','stt','Transcription',s.compatibility_profile,s.base_url,s.allow_insecure_http,s.authentication_mode,s.health_path,c.account FROM transcription_settings s JOIN credential_refs c ON c.purpose='stt' WHERE s.base_url <> '' AND NOT EXISTS(SELECT 1 FROM saved_connections WHERE purpose='stt')
`

func (q *Queries) SeedTranscriptionConnection(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedTranscriptionConnection)
	return err
}

const selectSavedConnection = `-- name: SelectSavedConnection :exec
INSERT INTO selected_connections(purpose,connection_id) VALUES(?,?) ON CONFLICT(purpose) DO UPDATE SET connection_id=excluded.connection_id
`

type SelectSavedConnectionParams struct {
	Purpose      string
	ConnectionID string
}

func (q *Queries) SelectSavedConnection(ctx context.Context, arg SelectSavedConnectionParams) error {
	_, err := q.db.ExecContext(ctx, selectSavedConnection, arg.Purpose, arg.ConnectionID)
	return err
}
