// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: managed_runtime.sql

package dbgen

import (
	"context"
)

const getManagedRuntime = `-- name: GetManagedRuntime :one
SELECT enabled, model, realtime FROM managed_runtime_preferences WHERE id = 1
`

type GetManagedRuntimeRow struct {
	Enabled  int64
	Model    string
	Realtime int64
}

func (q *Queries) GetManagedRuntime(ctx context.Context) (GetManagedRuntimeRow, error) {
	row := q.db.QueryRowContext(ctx, getManagedRuntime)
	var i GetManagedRuntimeRow
	err := row.Scan(&i.Enabled, &i.Model, &i.Realtime)
	return i, err
}

const putManagedRuntime = `-- name: PutManagedRuntime :exec
INSERT INTO managed_runtime_preferences (id, enabled, model, realtime)
VALUES (1, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET enabled = excluded.enabled, model = excluded.model, realtime = excluded.realtime
`

type PutManagedRuntimeParams struct {
	Enabled  int64
	Model    string
	Realtime int64
}

func (q *Queries) PutManagedRuntime(ctx context.Context, arg PutManagedRuntimeParams) error {
	_, err := q.db.ExecContext(ctx, putManagedRuntime, arg.Enabled, arg.Model, arg.Realtime)
	return err
}
