// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: managed_runtime.sql

package dbgen

import (
	"context"
)

const deleteManagedInstance = `-- name: DeleteManagedInstance :exec
DELETE FROM managed_runtime_instances WHERE id=?
`

func (q *Queries) DeleteManagedInstance(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteManagedInstance, id)
	return err
}

const listManagedInstances = `-- name: ListManagedInstances :many
SELECT id, name, provider, model, auto_start FROM managed_runtime_instances ORDER BY id LIMIT 9
`

func (q *Queries) ListManagedInstances(ctx context.Context) ([]ManagedRuntimeInstance, error) {
	rows, err := q.db.QueryContext(ctx, listManagedInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagedRuntimeInstance{}
	for rows.Next() {
		var i ManagedRuntimeInstance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Model,
			&i.AutoStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putManagedInstance = `-- name: PutManagedInstance :exec
INSERT INTO managed_runtime_instances(id,name,provider,model,auto_start) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,provider=excluded.provider,model=excluded.model,auto_start=excluded.auto_start
`

type PutManagedInstanceParams struct {
	ID        string
	Name      string
	Provider  string
	Model     string
	AutoStart int64
}

func (q *Queries) PutManagedInstance(ctx context.Context, arg PutManagedInstanceParams) error {
	_, err := q.db.ExecContext(ctx, putManagedInstance,
		arg.ID,
		arg.Name,
		arg.Provider,
		arg.Model,
		arg.AutoStart,
	)
	return err
}
