// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

type CleanupSetting struct {
	ID                                 int64
	GenerationOptionsLimitOutputTokens int64
	GenerationOptionsMaxOutputTokens   int64
	GenerationOptionsDisableReasoning  int64
	CompatibilityProfile               string
	Enabled                            int64
	BaseUrl                            string
	AllowInsecureHttp                  int64
	Model                              string
	Preset                             string
	SystemPrompt                       string
	Styling                            string
	Structure                          string
	Context                            string
	TimeoutSeconds                     int64
}

type CredentialGc struct {
	Account string
}

type CredentialRef struct {
	Purpose string
	Account string
}

type Initialization struct {
	ID     int64
	Source string
}

type PreferencesSetting struct {
	ID                      int64
	ToggleShortcut          string
	ShowShortcut            string
	HoldShortcut            string
	MicrophoneID            string
	MaxDurationSeconds      int64
	AutoInsert              int64
	StartWithWindows        int64
	ShowWindowOnLaunch      int64
	CheckForUpdates         int64
	SetupCompleted          int64
	UseMica                 int64
	AppearanceMode          string
	OverlayEnabled          int64
	OverlaySizePercent      int64
	OverlayOpacityPercent   int64
	OverlayTopOffset        int64
	OverlayGlowPercent      int64
	OverlayLayout           string
	OverlayAnchor           string
	OverlayVisibility       string
	OverlayMotion           string
	OverlaySurface          string
	OverlayVisualizer       string
	HistoryEnabled          int64
	VadEnabled              int64
	VadMode                 string
	VadActivitySilenceMs    int64
	SilenceTrimming         int64
	SpeechPaddingMs         int64
	AutoStopEnabled         int64
	AutoStopSilenceMs       int64
	AutoStopMinimumSpeechMs int64
	SilenceSplitting        int64
	SegmentSeconds          int64
	SegmentSilenceMs        int64
}

type RequestHeader struct {
	SettingsID int64
	Name       string
	Value      string
}

type SpeechSetting struct {
	ID                   int64
	CompatibilityProfile string
	Enabled              int64
	BaseUrl              string
	AllowInsecureHttp    int64
	AuthenticationMode   string
	Model                string
	Voice                string
	Speed                float64
	TimeoutSeconds       int64
}

type TranscriptionSetting struct {
	ID                                      int64
	CompatibilityProfile                    string
	BaseUrl                                 string
	AllowInsecureHttp                       int64
	AuthenticationMode                      string
	Model                                   string
	Language                                string
	HealthPath                              string
	TranscriptionTimeoutSeconds             int64
	FileTranscriptionTimeoutSeconds         int64
	TranscriptionOptionsPrompt              string
	TranscriptionOptionsHotwords            string
	TranscriptionOptionsTemperatureOverride int64
	TranscriptionOptionsTemperature         float64
}
