// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: realtime.sql

package dbgen

import (
	"context"
)

const getRealtime = `-- name: GetRealtime :one
SELECT id, enabled, compatibility_profile, model_profile, base_url, allow_insecure_http, authentication_mode, model, language, captions, vocabulary, boost FROM realtime_settings WHERE id=1
`

func (q *Queries) GetRealtime(ctx context.Context) (RealtimeSetting, error) {
	row := q.db.QueryRowContext(ctx, getRealtime)
	var i RealtimeSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.CompatibilityProfile,
		&i.ModelProfile,
		&i.BaseUrl,
		&i.AllowInsecureHttp,
		&i.AuthenticationMode,
		&i.Model,
		&i.Language,
		&i.Captions,
		&i.Vocabulary,
		&i.Boost,
	)
	return i, err
}

const putRealtime = `-- name: PutRealtime :exec
INSERT INTO realtime_settings(id,enabled,compatibility_profile,model_profile,base_url,allow_insecure_http,authentication_mode,model,language,captions,vocabulary,boost) VALUES(1,?,?,?,?,?,?,?,?,?,?,?)
ON CONFLICT(id) DO UPDATE SET enabled=excluded.enabled,compatibility_profile=excluded.compatibility_profile,model_profile=excluded.model_profile,base_url=excluded.base_url,allow_insecure_http=excluded.allow_insecure_http,authentication_mode=excluded.authentication_mode,model=excluded.model,language=excluded.language,captions=excluded.captions,vocabulary=excluded.vocabulary,boost=excluded.boost
`

type PutRealtimeParams struct {
	Enabled              int64
	CompatibilityProfile string
	ModelProfile         string
	BaseUrl              string
	AllowInsecureHttp    int64
	AuthenticationMode   string
	Model                string
	Language             string
	Captions             int64
	Vocabulary           string
	Boost                float64
}

func (q *Queries) PutRealtime(ctx context.Context, arg PutRealtimeParams) error {
	_, err := q.db.ExecContext(ctx, putRealtime,
		arg.Enabled,
		arg.CompatibilityProfile,
		arg.ModelProfile,
		arg.BaseUrl,
		arg.AllowInsecureHttp,
		arg.AuthenticationMode,
		arg.Model,
		arg.Language,
		arg.Captions,
		arg.Vocabulary,
		arg.Boost,
	)
	return err
}
