// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remembered_models.sql

package dbgen

import (
	"context"
)

const clearRememberedModels = `-- name: ClearRememberedModels :exec
DELETE FROM remembered_models
`

func (q *Queries) ClearRememberedModels(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearRememberedModels)
	return err
}

const listRememberedModels = `-- name: ListRememberedModels :many
SELECT connection_id,purpose,model,selected,profile,language,prompt,hotwords,temperature_override,temperature,limit_output_tokens,max_output_tokens,disable_reasoning,system_prompt,styling,structure,context,voice,speed FROM remembered_models ORDER BY connection_id,purpose,model LIMIT 9217
`

func (q *Queries) ListRememberedModels(ctx context.Context) ([]RememberedModel, error) {
	rows, err := q.db.QueryContext(ctx, listRememberedModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RememberedModel{}
	for rows.Next() {
		var i RememberedModel
		if err := rows.Scan(
			&i.ConnectionID,
			&i.Purpose,
			&i.Model,
			&i.Selected,
			&i.Profile,
			&i.Language,
			&i.Prompt,
			&i.Hotwords,
			&i.TemperatureOverride,
			&i.Temperature,
			&i.LimitOutputTokens,
			&i.MaxOutputTokens,
			&i.DisableReasoning,
			&i.SystemPrompt,
			&i.Styling,
			&i.Structure,
			&i.Context,
			&i.Voice,
			&i.Speed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putRememberedModel = `-- name: PutRememberedModel :exec
INSERT INTO remembered_models (connection_id,purpose,model,selected,profile,language,prompt,hotwords,temperature_override,temperature,limit_output_tokens,max_output_tokens,disable_reasoning,system_prompt,styling,structure,context,voice,speed) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type PutRememberedModelParams struct {
	ConnectionID        string
	Purpose             string
	Model               string
	Selected            int64
	Profile             string
	Language            string
	Prompt              string
	Hotwords            string
	TemperatureOverride int64
	Temperature         float64
	LimitOutputTokens   int64
	MaxOutputTokens     int64
	DisableReasoning    int64
	SystemPrompt        string
	Styling             string
	Structure           string
	Context             string
	Voice               string
	Speed               float64
}

func (q *Queries) PutRememberedModel(ctx context.Context, arg PutRememberedModelParams) error {
	_, err := q.db.ExecContext(ctx, putRememberedModel,
		arg.ConnectionID,
		arg.Purpose,
		arg.Model,
		arg.Selected,
		arg.Profile,
		arg.Language,
		arg.Prompt,
		arg.Hotwords,
		arg.TemperatureOverride,
		arg.Temperature,
		arg.LimitOutputTokens,
		arg.MaxOutputTokens,
		arg.DisableReasoning,
		arg.SystemPrompt,
		arg.Styling,
		arg.Structure,
		arg.Context,
		arg.Voice,
		arg.Speed,
	)
	return err
}
