// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remembered_models.sql

package dbgen

import (
	"context"
)

const clearRememberedModels = `-- name: ClearRememberedModels :exec
DELETE FROM remembered_models
`

func (q *Queries) ClearRememberedModels(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearRememberedModels)
	return err
}

const listRememberedModels = `-- name: ListRememberedModels :many
SELECT connection_id,purpose,model,selected,profile,prompt,temperature_override,temperature,limit_output_tokens,max_output_tokens,disable_reasoning,voice,speech_language,speech_instructions, nemo_disable_punctuation, nemo_normalize, nemo_profanity_filter, nemo_endpointing_ms FROM remembered_models ORDER BY connection_id,purpose,model LIMIT 16385
`

func (q *Queries) ListRememberedModels(ctx context.Context) ([]RememberedModel, error) {
	rows, err := q.db.QueryContext(ctx, listRememberedModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RememberedModel{}
	for rows.Next() {
		var i RememberedModel
		if err := rows.Scan(
			&i.ConnectionID,
			&i.Purpose,
			&i.Model,
			&i.Selected,
			&i.Profile,
			&i.Prompt,
			&i.TemperatureOverride,
			&i.Temperature,
			&i.LimitOutputTokens,
			&i.MaxOutputTokens,
			&i.DisableReasoning,
			&i.Voice,
			&i.SpeechLanguage,
			&i.SpeechInstructions,
			&i.NemoDisablePunctuation,
			&i.NemoNormalize,
			&i.NemoProfanityFilter,
			&i.NemoEndpointingMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putRememberedModel = `-- name: PutRememberedModel :exec
INSERT INTO remembered_models (connection_id,purpose,model,selected,profile,prompt,temperature_override,temperature,limit_output_tokens,max_output_tokens,disable_reasoning,voice,speech_language,speech_instructions, nemo_disable_punctuation, nemo_normalize, nemo_profanity_filter, nemo_endpointing_ms) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type PutRememberedModelParams struct {
	ConnectionID           string
	Purpose                string
	Model                  string
	Selected               int64
	Profile                string
	Prompt                 string
	TemperatureOverride    int64
	Temperature            float64
	LimitOutputTokens      int64
	MaxOutputTokens        int64
	DisableReasoning       int64
	Voice                  string
	SpeechLanguage         string
	SpeechInstructions     string
	NemoDisablePunctuation int64
	NemoNormalize          int64
	NemoProfanityFilter    int64
	NemoEndpointingMs      int64
}

func (q *Queries) PutRememberedModel(ctx context.Context, arg PutRememberedModelParams) error {
	_, err := q.db.ExecContext(ctx, putRememberedModel,
		arg.ConnectionID,
		arg.Purpose,
		arg.Model,
		arg.Selected,
		arg.Profile,
		arg.Prompt,
		arg.TemperatureOverride,
		arg.Temperature,
		arg.LimitOutputTokens,
		arg.MaxOutputTokens,
		arg.DisableReasoning,
		arg.Voice,
		arg.SpeechLanguage,
		arg.SpeechInstructions,
		arg.NemoDisablePunctuation,
		arg.NemoNormalize,
		arg.NemoProfanityFilter,
		arg.NemoEndpointingMs,
	)
	return err
}
