// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package dbgen

import (
	"context"
)

const completeCredentialGC = `-- name: CompleteCredentialGC :exec
DELETE FROM credential_gc WHERE account=?
`

func (q *Queries) CompleteCredentialGC(ctx context.Context, account string) error {
	_, err := q.db.ExecContext(ctx, completeCredentialGC, account)
	return err
}

const countCredentialGC = `-- name: CountCredentialGC :one
SELECT count(*) FROM credential_gc WHERE account NOT IN (SELECT credential_account FROM saved_connections)
`

func (q *Queries) CountCredentialGC(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCredentialGC)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCleanup = `-- name: GetCleanup :one
SELECT generation_options_limit_output_tokens, generation_options_max_output_tokens, generation_options_disable_reasoning, enabled, model, preset, system_prompt, styling, structure, context, timeout_seconds FROM cleanup_settings WHERE id=1
`

type GetCleanupRow struct {
	GenerationOptionsLimitOutputTokens int64
	GenerationOptionsMaxOutputTokens   int64
	GenerationOptionsDisableReasoning  int64
	Enabled                            int64
	Model                              string
	Preset                             string
	SystemPrompt                       string
	Styling                            string
	Structure                          string
	Context                            string
	TimeoutSeconds                     int64
}

func (q *Queries) GetCleanup(ctx context.Context) (GetCleanupRow, error) {
	row := q.db.QueryRowContext(ctx, getCleanup)
	var i GetCleanupRow
	err := row.Scan(
		&i.GenerationOptionsLimitOutputTokens,
		&i.GenerationOptionsMaxOutputTokens,
		&i.GenerationOptionsDisableReasoning,
		&i.Enabled,
		&i.Model,
		&i.Preset,
		&i.SystemPrompt,
		&i.Styling,
		&i.Structure,
		&i.Context,
		&i.TimeoutSeconds,
	)
	return i, err
}

const getCredentialRefs = `-- name: GetCredentialRefs :many
SELECT s.purpose, c.credential_account AS account FROM selected_connections s JOIN saved_connections c ON c.id=s.connection_id ORDER BY s.purpose
`

type GetCredentialRefsRow struct {
	Purpose string
	Account string
}

func (q *Queries) GetCredentialRefs(ctx context.Context) ([]GetCredentialRefsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCredentialRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCredentialRefsRow{}
	for rows.Next() {
		var i GetCredentialRefsRow
		if err := rows.Scan(&i.Purpose, &i.Account); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreferences = `-- name: GetPreferences :one
SELECT toggle_shortcut, show_shortcut, hold_shortcut, microphone_id, max_duration_seconds, auto_insert, start_with_windows, show_window_on_launch, check_for_updates, setup_completed, use_mica, appearance_mode, overlay_enabled, overlay_size_percent, overlay_opacity_percent, overlay_top_offset, overlay_glow_percent, overlay_layout, overlay_anchor, overlay_visibility, overlay_motion, overlay_surface, overlay_visualizer, history_enabled, vad_enabled, vad_mode, vad_activity_silence_ms, silence_trimming, speech_padding_ms, auto_stop_enabled, auto_stop_silence_ms, auto_stop_minimum_speech_ms, silence_splitting, segment_seconds, segment_silence_ms FROM preferences_settings WHERE id=1
`

type GetPreferencesRow struct {
	ToggleShortcut          string
	ShowShortcut            string
	HoldShortcut            string
	MicrophoneID            string
	MaxDurationSeconds      int64
	AutoInsert              int64
	StartWithWindows        int64
	ShowWindowOnLaunch      int64
	CheckForUpdates         int64
	SetupCompleted          int64
	UseMica                 int64
	AppearanceMode          string
	OverlayEnabled          int64
	OverlaySizePercent      int64
	OverlayOpacityPercent   int64
	OverlayTopOffset        int64
	OverlayGlowPercent      int64
	OverlayLayout           string
	OverlayAnchor           string
	OverlayVisibility       string
	OverlayMotion           string
	OverlaySurface          string
	OverlayVisualizer       string
	HistoryEnabled          int64
	VadEnabled              int64
	VadMode                 string
	VadActivitySilenceMs    int64
	SilenceTrimming         int64
	SpeechPaddingMs         int64
	AutoStopEnabled         int64
	AutoStopSilenceMs       int64
	AutoStopMinimumSpeechMs int64
	SilenceSplitting        int64
	SegmentSeconds          int64
	SegmentSilenceMs        int64
}

func (q *Queries) GetPreferences(ctx context.Context) (GetPreferencesRow, error) {
	row := q.db.QueryRowContext(ctx, getPreferences)
	var i GetPreferencesRow
	err := row.Scan(
		&i.ToggleShortcut,
		&i.ShowShortcut,
		&i.HoldShortcut,
		&i.MicrophoneID,
		&i.MaxDurationSeconds,
		&i.AutoInsert,
		&i.StartWithWindows,
		&i.ShowWindowOnLaunch,
		&i.CheckForUpdates,
		&i.SetupCompleted,
		&i.UseMica,
		&i.AppearanceMode,
		&i.OverlayEnabled,
		&i.OverlaySizePercent,
		&i.OverlayOpacityPercent,
		&i.OverlayTopOffset,
		&i.OverlayGlowPercent,
		&i.OverlayLayout,
		&i.OverlayAnchor,
		&i.OverlayVisibility,
		&i.OverlayMotion,
		&i.OverlaySurface,
		&i.OverlayVisualizer,
		&i.HistoryEnabled,
		&i.VadEnabled,
		&i.VadMode,
		&i.VadActivitySilenceMs,
		&i.SilenceTrimming,
		&i.SpeechPaddingMs,
		&i.AutoStopEnabled,
		&i.AutoStopSilenceMs,
		&i.AutoStopMinimumSpeechMs,
		&i.SilenceSplitting,
		&i.SegmentSeconds,
		&i.SegmentSilenceMs,
	)
	return i, err
}

const getSpeech = `-- name: GetSpeech :one
SELECT model_profile, enabled, model, voice, speed, timeout_seconds, speech_language, speech_instructions FROM speech_settings WHERE id=1
`

type GetSpeechRow struct {
	ModelProfile       string
	Enabled            int64
	Model              string
	Voice              string
	Speed              float64
	TimeoutSeconds     int64
	SpeechLanguage     string
	SpeechInstructions string
}

func (q *Queries) GetSpeech(ctx context.Context) (GetSpeechRow, error) {
	row := q.db.QueryRowContext(ctx, getSpeech)
	var i GetSpeechRow
	err := row.Scan(
		&i.ModelProfile,
		&i.Enabled,
		&i.Model,
		&i.Voice,
		&i.Speed,
		&i.TimeoutSeconds,
		&i.SpeechLanguage,
		&i.SpeechInstructions,
	)
	return i, err
}

const getTranscription = `-- name: GetTranscription :one
SELECT model_profile, model, language, transcription_timeout_seconds, file_transcription_timeout_seconds, transcription_options_prompt, transcription_options_temperature_override, transcription_options_temperature, nemo_disable_punctuation, nemo_normalize, nemo_profanity_filter, nemo_endpointing_ms FROM transcription_settings WHERE id=1
`

type GetTranscriptionRow struct {
	ModelProfile                            string
	Model                                   string
	Language                                string
	TranscriptionTimeoutSeconds             int64
	FileTranscriptionTimeoutSeconds         int64
	TranscriptionOptionsPrompt              string
	TranscriptionOptionsTemperatureOverride int64
	TranscriptionOptionsTemperature         float64
	NemoDisablePunctuation                  int64
	NemoNormalize                           int64
	NemoProfanityFilter                     int64
	NemoEndpointingMs                       int64
}

func (q *Queries) GetTranscription(ctx context.Context) (GetTranscriptionRow, error) {
	row := q.db.QueryRowContext(ctx, getTranscription)
	var i GetTranscriptionRow
	err := row.Scan(
		&i.ModelProfile,
		&i.Model,
		&i.Language,
		&i.TranscriptionTimeoutSeconds,
		&i.FileTranscriptionTimeoutSeconds,
		&i.TranscriptionOptionsPrompt,
		&i.TranscriptionOptionsTemperatureOverride,
		&i.TranscriptionOptionsTemperature,
		&i.NemoDisablePunctuation,
		&i.NemoNormalize,
		&i.NemoProfanityFilter,
		&i.NemoEndpointingMs,
	)
	return i, err
}

const pendingCredentialGC = `-- name: PendingCredentialGC :many
SELECT account FROM credential_gc WHERE account NOT IN (SELECT credential_account FROM saved_connections) ORDER BY account LIMIT 128
`

func (q *Queries) PendingCredentialGC(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, pendingCredentialGC)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var account string
		if err := rows.Scan(&account); err != nil {
			return nil, err
		}
		items = append(items, account)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putCleanup = `-- name: PutCleanup :exec
INSERT INTO cleanup_settings (id, generation_options_limit_output_tokens, generation_options_max_output_tokens, generation_options_disable_reasoning, enabled, model, preset, system_prompt, styling, structure, context, timeout_seconds)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET generation_options_limit_output_tokens=excluded.generation_options_limit_output_tokens, generation_options_max_output_tokens=excluded.generation_options_max_output_tokens, generation_options_disable_reasoning=excluded.generation_options_disable_reasoning, enabled=excluded.enabled, model=excluded.model, preset=excluded.preset, system_prompt=excluded.system_prompt, styling=excluded.styling, structure=excluded.structure, context=excluded.context, timeout_seconds=excluded.timeout_seconds
`

type PutCleanupParams struct {
	GenerationOptionsLimitOutputTokens int64
	GenerationOptionsMaxOutputTokens   int64
	GenerationOptionsDisableReasoning  int64
	Enabled                            int64
	Model                              string
	Preset                             string
	SystemPrompt                       string
	Styling                            string
	Structure                          string
	Context                            string
	TimeoutSeconds                     int64
}

func (q *Queries) PutCleanup(ctx context.Context, arg PutCleanupParams) error {
	_, err := q.db.ExecContext(ctx, putCleanup,
		arg.GenerationOptionsLimitOutputTokens,
		arg.GenerationOptionsMaxOutputTokens,
		arg.GenerationOptionsDisableReasoning,
		arg.Enabled,
		arg.Model,
		arg.Preset,
		arg.SystemPrompt,
		arg.Styling,
		arg.Structure,
		arg.Context,
		arg.TimeoutSeconds,
	)
	return err
}

const putPreferences = `-- name: PutPreferences :exec
INSERT INTO preferences_settings (id, toggle_shortcut, show_shortcut, hold_shortcut, microphone_id, max_duration_seconds, auto_insert, start_with_windows, show_window_on_launch, check_for_updates, setup_completed, use_mica, appearance_mode, overlay_enabled, overlay_size_percent, overlay_opacity_percent, overlay_top_offset, overlay_glow_percent, overlay_layout, overlay_anchor, overlay_visibility, overlay_motion, overlay_surface, overlay_visualizer, history_enabled, vad_enabled, vad_mode, vad_activity_silence_ms, silence_trimming, speech_padding_ms, auto_stop_enabled, auto_stop_silence_ms, auto_stop_minimum_speech_ms, silence_splitting, segment_seconds, segment_silence_ms)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET toggle_shortcut=excluded.toggle_shortcut, show_shortcut=excluded.show_shortcut, hold_shortcut=excluded.hold_shortcut, microphone_id=excluded.microphone_id, max_duration_seconds=excluded.max_duration_seconds, auto_insert=excluded.auto_insert, start_with_windows=excluded.start_with_windows, show_window_on_launch=excluded.show_window_on_launch, check_for_updates=excluded.check_for_updates, setup_completed=excluded.setup_completed, use_mica=excluded.use_mica, appearance_mode=excluded.appearance_mode, overlay_enabled=excluded.overlay_enabled, overlay_size_percent=excluded.overlay_size_percent, overlay_opacity_percent=excluded.overlay_opacity_percent, overlay_top_offset=excluded.overlay_top_offset, overlay_glow_percent=excluded.overlay_glow_percent, overlay_layout=excluded.overlay_layout, overlay_anchor=excluded.overlay_anchor, overlay_visibility=excluded.overlay_visibility, overlay_motion=excluded.overlay_motion, overlay_surface=excluded.overlay_surface, overlay_visualizer=excluded.overlay_visualizer, history_enabled=excluded.history_enabled, vad_enabled=excluded.vad_enabled, vad_mode=excluded.vad_mode, vad_activity_silence_ms=excluded.vad_activity_silence_ms, silence_trimming=excluded.silence_trimming, speech_padding_ms=excluded.speech_padding_ms, auto_stop_enabled=excluded.auto_stop_enabled, auto_stop_silence_ms=excluded.auto_stop_silence_ms, auto_stop_minimum_speech_ms=excluded.auto_stop_minimum_speech_ms, silence_splitting=excluded.silence_splitting, segment_seconds=excluded.segment_seconds, segment_silence_ms=excluded.segment_silence_ms
`

type PutPreferencesParams struct {
	ToggleShortcut          string
	ShowShortcut            string
	HoldShortcut            string
	MicrophoneID            string
	MaxDurationSeconds      int64
	AutoInsert              int64
	StartWithWindows        int64
	ShowWindowOnLaunch      int64
	CheckForUpdates         int64
	SetupCompleted          int64
	UseMica                 int64
	AppearanceMode          string
	OverlayEnabled          int64
	OverlaySizePercent      int64
	OverlayOpacityPercent   int64
	OverlayTopOffset        int64
	OverlayGlowPercent      int64
	OverlayLayout           string
	OverlayAnchor           string
	OverlayVisibility       string
	OverlayMotion           string
	OverlaySurface          string
	OverlayVisualizer       string
	HistoryEnabled          int64
	VadEnabled              int64
	VadMode                 string
	VadActivitySilenceMs    int64
	SilenceTrimming         int64
	SpeechPaddingMs         int64
	AutoStopEnabled         int64
	AutoStopSilenceMs       int64
	AutoStopMinimumSpeechMs int64
	SilenceSplitting        int64
	SegmentSeconds          int64
	SegmentSilenceMs        int64
}

func (q *Queries) PutPreferences(ctx context.Context, arg PutPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, putPreferences,
		arg.ToggleShortcut,
		arg.ShowShortcut,
		arg.HoldShortcut,
		arg.MicrophoneID,
		arg.MaxDurationSeconds,
		arg.AutoInsert,
		arg.StartWithWindows,
		arg.ShowWindowOnLaunch,
		arg.CheckForUpdates,
		arg.SetupCompleted,
		arg.UseMica,
		arg.AppearanceMode,
		arg.OverlayEnabled,
		arg.OverlaySizePercent,
		arg.OverlayOpacityPercent,
		arg.OverlayTopOffset,
		arg.OverlayGlowPercent,
		arg.OverlayLayout,
		arg.OverlayAnchor,
		arg.OverlayVisibility,
		arg.OverlayMotion,
		arg.OverlaySurface,
		arg.OverlayVisualizer,
		arg.HistoryEnabled,
		arg.VadEnabled,
		arg.VadMode,
		arg.VadActivitySilenceMs,
		arg.SilenceTrimming,
		arg.SpeechPaddingMs,
		arg.AutoStopEnabled,
		arg.AutoStopSilenceMs,
		arg.AutoStopMinimumSpeechMs,
		arg.SilenceSplitting,
		arg.SegmentSeconds,
		arg.SegmentSilenceMs,
	)
	return err
}

const putSpeech = `-- name: PutSpeech :exec
INSERT INTO speech_settings (id, model_profile, enabled, model, voice, speed, timeout_seconds, speech_language, speech_instructions)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET model_profile=excluded.model_profile, enabled=excluded.enabled, model=excluded.model, voice=excluded.voice, speed=excluded.speed, timeout_seconds=excluded.timeout_seconds, speech_language=excluded.speech_language, speech_instructions=excluded.speech_instructions
`

type PutSpeechParams struct {
	ModelProfile       string
	Enabled            int64
	Model              string
	Voice              string
	Speed              float64
	TimeoutSeconds     int64
	SpeechLanguage     string
	SpeechInstructions string
}

func (q *Queries) PutSpeech(ctx context.Context, arg PutSpeechParams) error {
	_, err := q.db.ExecContext(ctx, putSpeech,
		arg.ModelProfile,
		arg.Enabled,
		arg.Model,
		arg.Voice,
		arg.Speed,
		arg.TimeoutSeconds,
		arg.SpeechLanguage,
		arg.SpeechInstructions,
	)
	return err
}

const putTranscription = `-- name: PutTranscription :exec
INSERT INTO transcription_settings (id, model_profile, model, language, transcription_timeout_seconds, file_transcription_timeout_seconds, transcription_options_prompt, transcription_options_temperature_override, transcription_options_temperature, nemo_disable_punctuation, nemo_normalize, nemo_profanity_filter, nemo_endpointing_ms)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET model_profile=excluded.model_profile, model=excluded.model, language=excluded.language, transcription_timeout_seconds=excluded.transcription_timeout_seconds, file_transcription_timeout_seconds=excluded.file_transcription_timeout_seconds, transcription_options_prompt=excluded.transcription_options_prompt, transcription_options_temperature_override=excluded.transcription_options_temperature_override, transcription_options_temperature=excluded.transcription_options_temperature, nemo_disable_punctuation=excluded.nemo_disable_punctuation, nemo_normalize=excluded.nemo_normalize, nemo_profanity_filter=excluded.nemo_profanity_filter, nemo_endpointing_ms=excluded.nemo_endpointing_ms
`

type PutTranscriptionParams struct {
	ModelProfile                            string
	Model                                   string
	Language                                string
	TranscriptionTimeoutSeconds             int64
	FileTranscriptionTimeoutSeconds         int64
	TranscriptionOptionsPrompt              string
	TranscriptionOptionsTemperatureOverride int64
	TranscriptionOptionsTemperature         float64
	NemoDisablePunctuation                  int64
	NemoNormalize                           int64
	NemoProfanityFilter                     int64
	NemoEndpointingMs                       int64
}

func (q *Queries) PutTranscription(ctx context.Context, arg PutTranscriptionParams) error {
	_, err := q.db.ExecContext(ctx, putTranscription,
		arg.ModelProfile,
		arg.Model,
		arg.Language,
		arg.TranscriptionTimeoutSeconds,
		arg.FileTranscriptionTimeoutSeconds,
		arg.TranscriptionOptionsPrompt,
		arg.TranscriptionOptionsTemperatureOverride,
		arg.TranscriptionOptionsTemperature,
		arg.NemoDisablePunctuation,
		arg.NemoNormalize,
		arg.NemoProfanityFilter,
		arg.NemoEndpointingMs,
	)
	return err
}

const queueCredentialGC = `-- name: QueueCredentialGC :exec
INSERT INTO credential_gc(account) VALUES(?) ON CONFLICT(account) DO NOTHING
`

func (q *Queries) QueueCredentialGC(ctx context.Context, account string) error {
	_, err := q.db.ExecContext(ctx, queueCredentialGC, account)
	return err
}
