// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vocabulary.sql

package dbgen

import (
	"context"
)

const getVocabulary = `-- name: GetVocabulary :one
SELECT terms, voice, files, boost FROM vocabulary_settings WHERE id=1
`

type GetVocabularyRow struct {
	Terms string
	Voice int64
	Files int64
	Boost float64
}

func (q *Queries) GetVocabulary(ctx context.Context) (GetVocabularyRow, error) {
	row := q.db.QueryRowContext(ctx, getVocabulary)
	var i GetVocabularyRow
	err := row.Scan(
		&i.Terms,
		&i.Voice,
		&i.Files,
		&i.Boost,
	)
	return i, err
}

const putVocabulary = `-- name: PutVocabulary :exec
INSERT INTO vocabulary_settings(id,terms,voice,files,boost) VALUES(1,?,?,?,?)
ON CONFLICT(id) DO UPDATE SET terms=excluded.terms,voice=excluded.voice,files=excluded.files,boost=excluded.boost
`

type PutVocabularyParams struct {
	Terms string
	Voice int64
	Files int64
	Boost float64
}

func (q *Queries) PutVocabulary(ctx context.Context, arg PutVocabularyParams) error {
	_, err := q.db.ExecContext(ctx, putVocabulary,
		arg.Terms,
		arg.Voice,
		arg.Files,
		arg.Boost,
	)
	return err
}
