// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_transcription.sql

package dbgen

import (
	"context"
)

const getVoiceTranscription = `-- name: GetVoiceTranscription :one
SELECT realtime, model_profile, model, language, timeout_seconds, prompt, temperature_override, temperature, captions FROM voice_transcription_settings WHERE id=1
`

type GetVoiceTranscriptionRow struct {
	Realtime            int64
	ModelProfile        string
	Model               string
	Language            string
	TimeoutSeconds      int64
	Prompt              string
	TemperatureOverride int64
	Temperature         float64
	Captions            int64
}

func (q *Queries) GetVoiceTranscription(ctx context.Context) (GetVoiceTranscriptionRow, error) {
	row := q.db.QueryRowContext(ctx, getVoiceTranscription)
	var i GetVoiceTranscriptionRow
	err := row.Scan(
		&i.Realtime,
		&i.ModelProfile,
		&i.Model,
		&i.Language,
		&i.TimeoutSeconds,
		&i.Prompt,
		&i.TemperatureOverride,
		&i.Temperature,
		&i.Captions,
	)
	return i, err
}

const putVoiceTranscription = `-- name: PutVoiceTranscription :exec
INSERT INTO voice_transcription_settings (id, realtime, model_profile, model, language, timeout_seconds, prompt, temperature_override, temperature, captions)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET realtime=excluded.realtime, model_profile=excluded.model_profile, model=excluded.model, language=excluded.language, timeout_seconds=excluded.timeout_seconds, prompt=excluded.prompt, temperature_override=excluded.temperature_override, temperature=excluded.temperature, captions=excluded.captions
`

type PutVoiceTranscriptionParams struct {
	Realtime            int64
	ModelProfile        string
	Model               string
	Language            string
	TimeoutSeconds      int64
	Prompt              string
	TemperatureOverride int64
	Temperature         float64
	Captions            int64
}

func (q *Queries) PutVoiceTranscription(ctx context.Context, arg PutVoiceTranscriptionParams) error {
	_, err := q.db.ExecContext(ctx, putVoiceTranscription,
		arg.Realtime,
		arg.ModelProfile,
		arg.Model,
		arg.Language,
		arg.TimeoutSeconds,
		arg.Prompt,
		arg.TemperatureOverride,
		arg.Temperature,
		arg.Captions,
	)
	return err
}
