// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_transcription.sql

package dbgen

import (
	"context"
)

const clearVoiceHeaders = `-- name: ClearVoiceHeaders :exec
DELETE FROM voice_request_headers
`

func (q *Queries) ClearVoiceHeaders(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearVoiceHeaders)
	return err
}

const getVoiceHeaders = `-- name: GetVoiceHeaders :many
SELECT name,value FROM voice_request_headers ORDER BY name LIMIT 33
`

func (q *Queries) GetVoiceHeaders(ctx context.Context) ([]VoiceRequestHeader, error) {
	rows, err := q.db.QueryContext(ctx, getVoiceHeaders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceRequestHeader{}
	for rows.Next() {
		var i VoiceRequestHeader
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoiceTranscription = `-- name: GetVoiceTranscription :one
SELECT id, realtime, compatibility_profile, model_profile, base_url, allow_insecure_http, authentication_mode, model, language, health_path, timeout_seconds, prompt, hotwords, temperature_override, temperature, captions, vocabulary, boost FROM voice_transcription_settings WHERE id=1
`

func (q *Queries) GetVoiceTranscription(ctx context.Context) (VoiceTranscriptionSetting, error) {
	row := q.db.QueryRowContext(ctx, getVoiceTranscription)
	var i VoiceTranscriptionSetting
	err := row.Scan(
		&i.ID,
		&i.Realtime,
		&i.CompatibilityProfile,
		&i.ModelProfile,
		&i.BaseUrl,
		&i.AllowInsecureHttp,
		&i.AuthenticationMode,
		&i.Model,
		&i.Language,
		&i.HealthPath,
		&i.TimeoutSeconds,
		&i.Prompt,
		&i.Hotwords,
		&i.TemperatureOverride,
		&i.Temperature,
		&i.Captions,
		&i.Vocabulary,
		&i.Boost,
	)
	return i, err
}

const putVoiceHeader = `-- name: PutVoiceHeader :exec
INSERT INTO voice_request_headers(name,value) VALUES(?,?)
`

type PutVoiceHeaderParams struct {
	Name  string
	Value string
}

func (q *Queries) PutVoiceHeader(ctx context.Context, arg PutVoiceHeaderParams) error {
	_, err := q.db.ExecContext(ctx, putVoiceHeader, arg.Name, arg.Value)
	return err
}

const putVoiceTranscription = `-- name: PutVoiceTranscription :exec
INSERT INTO voice_transcription_settings(id,realtime,compatibility_profile,model_profile,base_url,allow_insecure_http,authentication_mode,model,language,health_path,timeout_seconds,prompt,hotwords,temperature_override,temperature,captions,vocabulary,boost) VALUES(1,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
ON CONFLICT(id) DO UPDATE SET realtime=excluded.realtime,compatibility_profile=excluded.compatibility_profile,model_profile=excluded.model_profile,base_url=excluded.base_url,allow_insecure_http=excluded.allow_insecure_http,authentication_mode=excluded.authentication_mode,model=excluded.model,language=excluded.language,health_path=excluded.health_path,timeout_seconds=excluded.timeout_seconds,prompt=excluded.prompt,hotwords=excluded.hotwords,temperature_override=excluded.temperature_override,temperature=excluded.temperature,captions=excluded.captions,vocabulary=excluded.vocabulary,boost=excluded.boost
`

type PutVoiceTranscriptionParams struct {
	Realtime             int64
	CompatibilityProfile string
	ModelProfile         string
	BaseUrl              string
	AllowInsecureHttp    int64
	AuthenticationMode   string
	Model                string
	Language             string
	HealthPath           string
	TimeoutSeconds       int64
	Prompt               string
	Hotwords             string
	TemperatureOverride  int64
	Temperature          float64
	Captions             int64
	Vocabulary           string
	Boost                float64
}

func (q *Queries) PutVoiceTranscription(ctx context.Context, arg PutVoiceTranscriptionParams) error {
	_, err := q.db.ExecContext(ctx, putVoiceTranscription,
		arg.Realtime,
		arg.CompatibilityProfile,
		arg.ModelProfile,
		arg.BaseUrl,
		arg.AllowInsecureHttp,
		arg.AuthenticationMode,
		arg.Model,
		arg.Language,
		arg.HealthPath,
		arg.TimeoutSeconds,
		arg.Prompt,
		arg.Hotwords,
		arg.TemperatureOverride,
		arg.Temperature,
		arg.Captions,
		arg.Vocabulary,
		arg.Boost,
	)
	return err
}
